language: go

go:
  - 1.6.2

sudo: false

before_install:
  - git config --global user.email "contact@5minlab.com"
  - git config --global user.name "travis-ci"
  - git config push.default simple
  - mkdir -p .travis
  - openssl aes-256-cbc -K $encrypted_8c393341f536_key -iv $encrypted_8c393341f536_iv -in 5minlab_rsa.enc -out .travis/id_rsa -d
  - chmod 600 .travis/id_rsa
  - eval `ssh-agent -s`
  - ssh-add .travis/id_rsa

install:
  - go get -u -v github.com/spf13/hugo

script:
  - git remote remove origin
  - git remote add origin git@github.com:5minlab/5minlab.github.io.git
  - git fetch origin
  - ./build_site.sh
  - mv public /tmp
  - git checkout master
  - cp -r /tmp/public/* .
  - git add .
  - git commit -a -m "add new site content"
  - git push origin master --quiet

branches:
  only:
    - source

notifications:
  email: false
